language: android
sudo: required
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
    - add-on
    - extra
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
script: "./gradlew :FileBrowser:assembleRelease"
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
before_install:
  - sudo mkdir $ANDROID_HOME/licenses
  - echo -e '\\n8933bad161af4178b1185d1a37fbf41ea5269c55' | sudo tee $ANDROID_HOME/licenses/android-sdk-license
  - chmod +x gradlew
  - cp local.properties.ci local.properties