language: android
android:
  components:
  - tools
  - build-tools-25.0.2
  - android-25
  - extra-google-m2repository
  - extra-android-m2repository
script: "./gradlew build"
before_install:
- chmod +x gradlew
