language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - build-tools-25.0.2
  - android-25
  - extra-google-m2repository
  - extra-android-m2repository
script: "./gradlew :FileBrowser:assembleRelease"
before_install:
- chmod +x gradlew
- cp local.properties.ci local.properties